# Generated by Django 5.1.2 on 2024-10-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(upload_to='hotel_images'),
        ),
    ]
