# Generated by Django 5.1.2 on 2024-10-21 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel_site', '0002_alter_hotelimage_hotel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to='hotel_site.hotel'),
        ),
        migrations.AlterField(
            model_name='hotelimage',
            name='hotel_image',
            field=models.ImageField(upload_to='hotel_images/'),
        ),
        migrations.AlterField(
            model_name='imageroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='hotel_site.room'),
        ),
    ]
